<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>rsslounge aggregator</title>
    
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="language" content="<?PHP echo Zend_Registry::get('session')->language ?>" />
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="initial-scale=1.0">
    <meta name="viewport" content="width=320.1">
    <meta name="apple-mobile-web-app-capable" content="yes" />
<!-- iPhone 4 Retina -->
    <link href="apple-touch-startup-image-640x920.png" media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">
<!-- iPhone 5 -->
    <link href="apple-touch-startup-image-640x1096.png" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">
<!-- iPad (portrait) -->
    <link rel="apple-touch-startup-image" media="(device-width: 768px) and (orientation: portrait)" href="apple-touch-startup-image-768x1004.png">
<!-- iPad (landscape) -->
    <link rel="apple-touch-startup-image" media="(device-width: 768px) and (orientation: landscape)" href="apple-touch-startup-image-748x1024.png">

    
    <link rel="apple-touch-icon" href="apple-touch-icon-57x57.png" /> 
    <link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png" /> 
    <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="apple-touch-icon-144x144.png" />

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" />
    <?PHP
        echo $this->minifycss( array(
            "stylesheets/datepicker.css",
            "stylesheets/impromptu.css",
            "stylesheets/jquery.jgrowl.min.css",
            "stylesheets/tipsy.css",
            "stylesheets/ui.selectmenu.css",
            "stylesheets/style.css",
	    "stylesheets/style_iPhone.css",
	    "stylesheets/style_iPad.css"
        ));
    ?>
    <link rel="stylesheet" media="screen, handheld, projection, tv" href="stylesheets/snap.css?2013071645" />
</head>

<body class="snapjs-left <?PHP echo ($this->isIpad) ? 'ipad' : ''; ?>">
<div id="landscape"><p><b>Rotate Device to Portrait</b></p></div>
<div id="Menu" class="snap-drawers">
        <!-- feed list -->
        <ul id="feeds-list">
            <?PHP echo $this->render("index/feedlist." . Zend_Controller_Action_HelperBroker::getStaticHelper('viewRenderer')->getViewSuffix()); ?>
        </ul>
        <!-- progressbar -->
        <div id="progress">
            <div id="progress-feed"></div>
            <div id="progressbar"></div>
        </div>
        
        <!-- stats -->
        <ul id="stats">
            <li><?PHP echo $this->translate('all items'); ?> <span class="all"><?PHP echo $this->all; ?></span></li>
            <li><?PHP echo $this->translate('unread items'); ?> <span class="unread"><?PHP echo $this->unread; ?></span></li>
            <li><?PHP echo $this->translate('read items'); ?> <span class="read"><?PHP echo $this->read; ?></span></li>
            <li><?PHP echo $this->translate('feeds'); ?> <span class="feeds"><?PHP echo $this->amountfeeds; ?></span></li>
        </ul>
</div>
    <!-- header -->
    <div id="header" style="top:0px;">
        <div id="header-left"></div>
        <div id="header-content">
            <h1 onclick="location.reload();"><span>rssLounge aggregator</span></h1>
            
            <div id="prio">
                <label><?PHP echo $this->translate('Priority'); ?>: <span></span></label>
                <div id="slider"></div>
            </div>
            
            <a id="menue-button"><span><?PHP echo $this->translate('main menue'); ?></span></a>
        </div>
        <div id="header-right"></div>
    </div>

    <!-- top filter settings -->
            <div id="filter">
            
                <?PHP if(Zend_Registry::get('session')->authenticated===true) : ?>
                <ul id="actions">
                    <li><input type="button" value="<?PHP echo $this->translate('mark all as read'); ?>" id="markall" /></li>
                    <li><input type="button" value="<?PHP echo $this->translate('unstarr all'); ?>" id="unstarrall" /></li>
                </ul>
                <?PHP endif; ?>
                
                <div id="filter-options">
                    <select name="sort" id="sort">
                        <option value="date" <?PHP if(Zend_Registry::get('session')->sort=='date') : ?>selected="selected"<?PHP endif; ?>><?PHP echo $this->translate('first new'); ?></option>
                        <option value="dateasc" <?PHP if(Zend_Registry::get('session')->sort=='dateasc') : ?>selected="selected"<?PHP endif; ?>><?PHP echo $this->translate('first old'); ?></option>
                        <?PHP /*<option value="priority" <?PHP if(Zend_Registry::get('session')->sort=='priority') : ?>selected="selected"<?PHP endif; ?>><?PHP echo $this->translate('priority ascending'); ?></option>*/ ?>
                        <option value="priorityasc" <?PHP if(Zend_Registry::get('session')->sort=='priorityasc') : ?>selected="selected"<?PHP endif; ?>><?PHP echo $this->translate('priority descending'); ?></option>
                    </select>

                    <select name="unread" id="unread">
                        <option value="0" <?PHP if(Zend_Registry::get('session')->unread==0) : ?>selected="selected"<?PHP endif; ?>><?PHP echo $this->translate('all'); ?></option>
                        <option value="1" <?PHP if(Zend_Registry::get('session')->unread==1) : ?>selected="selected"<?PHP endif; ?>><?PHP echo $this->translate('only unread'); ?></option>
                    </select>
                    
                    <select name="view" id="view">
                        <option value="both" <?PHP if(Zend_Registry::get('session')->view=='both') : ?>selected="selected"<?PHP endif; ?>><?PHP echo $this->translate('images and messages'); ?></option>
                        <option value="messages" <?PHP if(Zend_Registry::get('session')->view=='messages') : ?>selected="selected"<?PHP endif; ?>><?PHP echo $this->translate('only messages'); ?></option>
                        <option value="multimedia" <?PHP if(Zend_Registry::get('session')->view=='multimedia') : ?>selected="selected"<?PHP endif; ?>><?PHP echo $this->translate('only images'); ?></option>
                    </select>
                </div>
            </div>
            
<div id="container" class="snap-content">
    
    
    <!-- main menue -->
    <ul id="menue" class="ui-corner-all ui-widget-content">
        <?PHP if(Zend_Registry::get('session')->authenticated===true) : ?>
            <li><a class="settings"><?PHP echo $this->translate('Settings'); ?></a></li>
            <li><a class="categories"><?PHP echo $this->translate('Categories'); ?></a></li>
            <li><a id="opml-import"><?PHP echo $this->translate('OPML Import'); ?></a></li>
            <li><a id="opml-export"><?PHP echo $this->translate('OPML Export'); ?></a></li>
            <li><a id="errormessages"><?PHP echo $this->translate('Errormessages'); ?></a></li>
        <?PHP endif; ?>
            <li class="<?PHP if(!isset($this->logout) && !isset($this->login)) echo 'last'; ?>"><a class="about"><?PHP echo $this->translate('About'); ?></a></li>
        
        <?PHP if(isset($this->logout)) : ?>
            <li class="last"><a class="logout"><?PHP echo $this->translate('Logout'); ?></a></li>
        <?PHP endif; ?>
        
        <?PHP if(isset($this->login)) : ?>
            <li class="last"><a class="login"><?PHP echo $this->translate('Login'); ?></a></li>
        <?PHP endif; ?>
    </ul>
    
    
    <!-- main area -->
    <div id="wrapper">
        <div id="content">
            
            
            
            <div id="items">
                <?PHP echo $this->render("item/list." . Zend_Controller_Action_HelperBroker::getStaticHelper('viewRenderer')->getViewSuffix()); ?>
            </div>
                  
        </div>
    </div>
    

    <!-- feed navigation -->
    <div id="feeds">
    
        <!-- add show hide feeds -->
        <ul id="feedsmenue">
            <?PHP if(Zend_Registry::get('session')->authenticated===true) : ?>
            <li><a class="add"><span><?PHP echo $this->translate('add new feed'); ?></span></a></li>
            <?PHP endif; ?>
            <li><a class="date <?PHP if(Zend_Registry::get('session')->dateFilter==1) echo 'active' ?>"><span><?PHP echo $this->translate('date'); ?></span></a></li>
            <li><a class="show" title="<?PHP echo $this->translate('Show all Feeds'); ?>"><span><?PHP echo $this->translate('Show all Feeds'); ?></span></a></li>
            <li><a class="hide" title="<?PHP echo $this->translate('Hide all Feeds'); ?>"><span><?PHP echo $this->translate('Hide all Feeds'); ?></span></a></li>
        </ul>

        <!-- calendar filter -->
        <div id="calendar">
        
        </div>

        <!-- feed list -->
        <ul id="feeds-list">
            <?PHP echo $this->render("index/feedlist." . Zend_Controller_Action_HelperBroker::getStaticHelper('viewRenderer')->getViewSuffix()); ?>
        </ul>
        
        <!-- search remove field -->
        <div class="search">
            <?PHP echo $this->translate('Search for'); ?> '<span class="search-term"></span>' <a title="<?PHP echo $this->translate('remove search'); ?>">
            <span><?PHP echo $this->translate('remove search'); ?></span></a>
        </div>
        
        
        <!-- progressbar -->
        <div id="progressb">
            <div id="progress-feedb"></div>
            <div id="progressbarb"></div>
        </div>
        
        <!-- stats -->
        <ul id="stats">
            <li><?PHP echo $this->translate('all items'); ?> <span class="all"><?PHP echo $this->all; ?></span></li>
            <li><?PHP echo $this->translate('unread items'); ?> <span class="unread"><?PHP echo $this->unread; ?></span></li>
            <li><?PHP echo $this->translate('read items'); ?> <span class="read"><?PHP echo $this->read; ?></span></li>
            <li><?PHP echo $this->translate('feeds'); ?> <span class="feeds"><?PHP echo $this->amountfeeds; ?></span></li>
        </ul>
    </div>
    
    
    <div id="extra">
        
    </div>
    
    
    <div id="footer">
        rsslounge aggregator <?PHP echo $this->version ?><br />
        <a href="http://rsslounge.aditu.de">http://rsslounge.aditu.de</a><br />
        icons by <a href="http://dryicons.com/">dryicons.com</a>
    </div>
</div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script> 
<?PHP
    echo $this->minifyjs( array(
        "javascript/addtouch.js",
        "javascript/datepicker.js",
        "javascript/jquery-impromptu.2.8.min.js",
        "javascript/jquery.jgrowl.min.js",
        "javascript/ajaxupload.3.5.js",
        "javascript/jquery.tipsy.js",
        "javascript/shortcut-2.01.B.js",
        "javascript/ui.selectmenu.js",
        "javascript/base.js",
        "javascript/events.js",
        "javascript/dialogs.js",
        "javascript/refresh.js",
        "javascript/locale/" . Zend_Registry::get('session')->language . ".js"
    ));
    
?>
<script type="text/javascript" src="javascript/snap.min.js?201307101630"></script>
<script type="text/javascript">
    rsslounge.settings = <?PHP echo Zend_Json::encode(Zend_Registry::get('session')->getIterator()) ?>;
    rsslounge.init('<?PHP echo $this->newfeed ?>');    


var snapper = new Snap({
  element: document.getElementById('container'),
  disable: 'right',
  hyperextensible: false,
  tapToClose:true,
  slideIntent: 20,
  maxPosition: 200,
  minPosition: 0,
  slideIntent: 20
});

$(window).scroll(function(){
	if($(window).scrollTop()==$(document).height() - $(window).height()){
		if($("li.more").length>0){
			$("li.more").each(function(i){this.click(); return false;});
		}
	}
});
    // Listen for resize changes
    window.addEventListener("resize", function() {
 
          if( window.outerWidth > window.outerHeight && $(window).height() < 481)
          {
              window.scrollTo(1,1);
              $('#landscape').show();
              lockScroll();
          }
          else{
               $('#landscape').hide();
               unLockScroll();
          }
 
 }, false);
function lockScroll()
{
     $(document).bind("touchmove",function(event){
                        event.preventDefault();
     });
}
 
function unLockScroll()
{
    $(document).unbind("touchmove");
}
</script>
<!--<script src='javascript/jquery.pull-to-refresh.js'></script>
    <script>
      $(document).ready(function(){
        $('#wrapper').pull_to_refresh({
          refresh: function(stoploading){
            	location.reload();
		stoploading();
          }
        });
      });
    </script>-->
</body>
</html>
