<li id="item_<?PHP echo $this->id ?>" class="<?PHP echo $this->unread==1 ? 'unread' : '' ?>">
    <div style="display:block">
    <?PHP if(Zend_Registry::get('session')->authenticated===true) : ?>
    <a class="starr-message <?PHP echo $this->starred==1 ? 'active' : '' ?>" title="<?PHP echo $this->translate('starr') ?>"><span><?PHP echo $this->translate('starr') ?></span></a>
    <!--<a class="mark-message <?PHP echo $this->unread==1 ? 'active' : '' ?>"><span><?PHP echo $this->translate('mark as read') ?></span></a>-->
    <?PHP endif; ?>
    <!--<?PHP if(Zend_Registry::get('config')->cache->enable==1 && Zend_Registry::get('config')->cache->iconcaching==1) : ?>
        <div class="icon-message" style="background:url(<?PHP echo Zend_Registry::get('config')->favicons->url . Zend_Registry::get('config')->cache->icons ?>);
                    background-position:0 -<?PHP $pos = Zend_Controller_Action_HelperBroker::getStaticHelper('icon')->getFeedsIconPosition(); echo $pos[$this->feed]*16?>px;"></div>
    <?PHP else : ?>
        <img src="<?PHP echo Zend_Registry::get('config')->favicons->url . $this->icon ?>" alt="<?PHP echo $this->name ?>" title="<?PHP echo $this->name ?>" width="16" height="16" />
    <?PHP endif; ?>-->
    <?PHP 
    $date = new Zend_Date($this->datetime, null, 'fr-FR');
    $today = new Zend_Date('en_US');
    $diff = $today->getTimestamp() - $date->getTimestamp();
    switch(1)
    {
        case ($diff < 60):
        $count = $diff;
        if ($diff == 1)
            $suffix = "second";
        else
            $suffix = "seconds";
        break;
        case ($diff > 60 && $diff < 3600):
        $count = floor($diff/60);
        if ($count == 1)
            $suffix = "minute";
        else
            $suffix = "minutes";
        break;
        case ($diff > 3600 && $diff < 86400):
        $count = floor($diff/3600);
        if ($count == 1)
            $suffix = "hour";
        else
            $suffix = "hours";
        break;
        case ($diff > 86400 && $diff < 2629743):
        $count = floor($diff/86400);
        if ($count == 1)
            $suffix = "day";
        else
            $suffix = "days";
        break;
        case ($diff > 2629743 && $diff < 31556926):
        $count = floor($diff/2629743);
        if ($count == 1)
            $suffix = "month";
        else
            $suffix = "months";
        break;
        case ($diff > 31556926):
        $count = floor($diff/31556926);
        if ($count == 1)
            $suffix = "year";
        else
            $suffix = "years";
        break;
    }
    if ($count == 1)
        $count = 'A';
    $stringDate = $count.' '.$suffix.' ago.';
    ?>
    <span title="<?PHP echo $date->toString('d.MM.YYYY HH:mm'); ?>"><?PHP echo $stringDate; ?></span>
    <a href="<?PHP echo $this->link ?>" class="link">&raquo; <?PHP echo $this->name ?> </a>
    <h2 <?PHP echo Zend_Registry::get('session')->openitems==1 ? 'class="opened"' : '' ?>>
        <?PHP 
            $title = $this->highlite($this->title, Zend_Registry::get('search'));
            echo strlen(trim($title))==0 ? '['.$this->translate('no title').']' : $title;
        ?>
    </h2>
</div>
    <div class="content <?PHP echo Zend_Registry::get('session')->openitems!=1 ? 'closed' : '' ?>">
        <?PHP 
            if(Zend_Registry::get('session')->openitems==1)
                echo $this->highlite($this->content, Zend_Registry::get('search'));
            else
                echo $this->lazyimg( $this->highlite($this->content, Zend_Registry::get('search')) );
        ?>
    </div>
    <!--<span class="date">
    <?PHP echo $date->toString('d.MM.'); ?>
    </span>-->
</li>